!: BOLT 3
!: AUTO HELLO

C: RUN "CALL dbms.cluster.routing.getRoutingTable($context)" {"context": null} {}
   PULL_ALL
S: SUCCESS {"fields": ["ttl", "servers"]}
   RECORD [6000, [{"addresses": ["127.0.0.1:9001"],"role": "WRITE"}, {"addresses": ["127.0.0.1:9002","127.0.0.1:9003"], "role": "READ"},{"addresses": ["127.0.0.1:9001","127.0.0.1:9002","127.0.0.1:9003"], "role": "ROUTE"}]]
   SUCCESS {}
C: GOODBYE
S: <EXIT>
