#!/usr/bin/env bash

set -Eeuo pipefail

grep_not(){ ! grep "${@}"; return $?;}

verlte() {
    [ "$1" = "$(echo -e "$1\n$2" | sort -V | head -n1)" ]
}

verlt() {
    [ "$1" = "$2" ] && return 1 || verlte $1 $2
}

go_version=$(go version | grep -o "go\([0-9.]\)\+" | grep -o "\([0-9.]\)\+")
staticcheck_version="latest"
if verlt $go_version "1.24.0"; then
	>&2 echo "Project requires go1.24 or newer"
    exit 1
fi

tags="\
internal_neo4j_go_driver_testkit,\
internal_neo4j_go_driver_time_mock\
"

echo "# pre-commit hook"
printf '%-15s' "## staticcheck "
cd "$(mktemp -d)" && go install honnef.co/go/tools/cmd/staticcheck@"${staticcheck_version}" && cd - > /dev/null
"${GOBIN:-$(go env GOPATH)/bin}"/staticcheck -tags "$tags" ./...
echo "✅"

printf '%-15s' "## go vet "
go vet -tags "$tags" ./...
echo "✅"

printf '%-15s' "## go test "
go test -short ./neo4j/... | grep_not --invert-match --fixed-strings --regexp='?' --regexp='ok' # only show failures
echo "✅"
