name: Forward commits as PRs
on:
  push:
    branches: ['4.3']
jobs:
  commit-forward:
    runs-on: ubuntu-latest
    steps:
      - name: pull-request-action
        uses: vsoch/pull-request-action@1.0.18
        env:
          GITHUB_TOKEN: ${{ secrets.FORWARD_TOKEN }}
          # source
          PULL_REQUEST_FROM_BRANCH: "neo4j:4.3"
          # target
          PULL_REQUEST_REPOSITORY: neo4j-drivers/neo4j-go-driver
          PULL_REQUEST_BRANCH: "4.3"
